exclude: ['README.md','assets/latex', 'hw_fa2017']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2019fa-cmpt-413-d1/"
semcode: 1187
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Dec 3, 2019"
midterm: "TBD"
instructor: anoop
tas:
  - name: Yilong (Jetic) Gu 
    email: jeticg
  - name: "Nishant Kambhatla"
    email: nkambhat
hwdates:
  - hw: "0"
    startdate: "Sep 11, 2019"
    deadline: "Sep 18, 2019"
  - hw: "1"
    startdate: "Sep 18, 2019"
    deadline: "Oct 2, 2019"
  - hw: "2"
    startdate: "Oct 2, 2019"
    deadline: "Oct 16, 2019"
  - hw: "3"
    startdate: "Oct 16, 2019"
    deadline: "Nov 6, 2019"
  - hw: "4"
    startdate: "Nov 6, 2019"
    deadline: "Nov 20, 2019"
  - hw: "project"
    startdate: "Nov 6, 2019"
    deadline: "Dec 10, 2019 2pm-5pm"
