exclude: ['README.md', 'assets/latex/', 'archive']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2022fa-cmpt-413-x1/"
canvas: "https://canvas.sfu.ca/courses/64917"
gradescope: "https://www.gradescope.ca/courses/7736"
semcode: 1227
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Dec 6, 2022"
midterm: "None"
instructor: angelx
officehour: "Tue 11am-12pm"
tas:
  - name: "Han-Hung Lee"
    email: hla300
    officehour: "Mon 10am-11am"
  - name: "Hanxiao (Shawn) Jiang"
    email: hja40
    officehour: "Fri 9am-10am"
  - name: "Yiming Zhang"
    email: yza440
    officehour: "Wed 10am-11am"
tutorials:
  - tutorial: "0"
    title: "Review of a) probability, linear algebra and calculus and b) useful python/unix commands"
    components: ["Probability, linear algebra and calculus", "Python/numpy/unix"]
  - tutorial: "1"
    title: "Building language models"
  - tutorial: "2"
    title: "Building classifiers with pytorch"
  - tutorial: "3"
    title: "Neural BoW with pytorch"
    components: ["Neural BoW with pytorch", "Optimization and backprop"]
  - tutorial: "4"
    title: "Using static word embeddings"
  - tutorial: "5"
    title: "Neural language models with BoW/Fixed Window FFN"
  - tutorial: "6"
    title: "Using RNNs in pytorch"
  - tutorial: "7"
    title: "Training/debugging networks and running experiments"
  - tutorial: "8"
    title: "Using Transformers in pytorch"
group:
  minsize: 1
  maxsize: 3
hwdates:
  - hw: "0"
    startdate: "Sept 12, 2022"
    deadline: "Sept 16, 2022"
    coursys: https://coursys.sfu.ca/2022fa-cmpt-413-x1/pages/HWC-0/view
  - hw: "1"
    startdate: "Sept 16, 2022"
    deadline: "Sept 30, 2022"
  - hw: "2"
    startdate: "Sept TBD, 2022"
    deadline: "Oct TBD, 2022"
  - hw: "3"
    startdate: "Oct TBD, 2022"
    deadline: "Oct TBD, 2022"
  - hw: "4"
    startdate: "Oct TBD, 2022"
    deadline: "Nov TBD, 2022"
  - hw: "project"
    startdate: "Oct TBD, 2022"
    deadline: "Dec TBD, 2022"
    time: "Poster session: ???"
    location: "TBD"
    abstract: "Oct TBD, 2022"
    proposal: "Oct TBD, 2022"
    milestone: "Nov TBD, 2022"
    poster: "Video due on Dec TBD, 2022"
