exclude: ['README.md', 'assets/latex/', 'archive', 'venv']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2024sp-cmpt-413-x1/"
forumname: Coursys Discussion Forum
forum: "https://coursys.sfu.ca/2024sp-cmpt-413-x1/forum/"
canvas: "none"
gradescope: "https://www.gradescope.ca/courses/7736"
semcode: 1241
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Apr 10, 2024"
midterm: "None"
instructor: angelx
officehour: "Wed 1:30pm-2:30pm"
tas:
  - name: "Yiming Zhang"
    email: yza440
    officehour: "TBD"
  - name: "ZeMing Gong"
    email: zmgong
    officehour: "TBD"
  - name: "Xiaohao Sun"
    email: xsa55
    officehour: "TBD"
tutorials:
  - tutorial: "0"
    title: "Review of a) probability, linear algebra and calculus and b) useful python/unix commands"
    components: ["Probability, linear algebra and calculus", "Python/numpy/unix"]
  - tutorial: "1"
    title: "Building language models"
  - tutorial: "2"
    title: "Learning pytorch"
  - tutorial: "3"
    title: "Building classifiers with pytorch"
  - tutorial: "4"
    title: "Neural BoW with pytorch"
    components: ["Neural BoW with pytorch", "Optimization and backprop"]
  - tutorial: "5"
    title: "Using static word embeddings"
  - tutorial: "6"
    title: "Neural language models with BoW/Fixed Window FFN"
  - tutorial: "7"
    title: "Using RNNs in pytorch"
  - tutorial: "8"
    title: "Training/debugging networks and running experiments"
  - tutorial: "9"
    title: "Using Transformers in pytorch"
  - tutorial: "10"
    title: "Prompting large language models"
group:
  minsize: 2
  maxsize: 3
hwdates:
  - hw: "0"
    startdate: "Jan 8, 2024"
    deadline: "Jan 17, 2024"
    canvas: https://canvas.sfu.ca/courses/75055/assignments/831465
  - hw: "1"
    startdate: "Jan 17, 2024"
    deadline: "Jan 31, 2024"
    canvas: https://canvas.sfu.ca/courses/75055/assignments/831466
  - hw: "2"
    startdate: "Jan 31, 2024"
    deadline: "Feb 14, 2024"
    canvas: https://canvas.sfu.ca/courses/75055/assignments/831467
  - hw: "3"
    startdate: "Feb 14, 2024"
    deadline: "Feb 28, 2024"
    canvas: https://canvas.sfu.ca/courses/75055/assignments/831468
  - hw: "4"
    startdate: "Feb 28, 2024"
    deadline: "Mar  13, 2024"
    canvas: https://canvas.sfu.ca/courses/75055/assignments/831469
  - hw: "project"
    startdate: "Feb 1, 2024"
    deadline: "Apr 10, 2024"
    time: "Poster session: ???"
    location: "TBD"
    abstract: "Feb 15, 2024"
    proposal: "Feb 29, 2024"
    milestone: "Mar 21, 2024"
    poster: "Video due on Apr 6, 2024"
hwsubmit:
  name: "Canvas"
