exclude: ['README.md', 'assets/latex/', 'archive']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2020sp-cmpt-825-g1/"
piazza: "https://piazza.com/sfu.ca/spring2020/cmpt825"
semcode: 1201
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Apr 9, 2020"
midterm: "Feb 25, 2020"
instructor: angelx
officehour: "Fri 10:30-11:30am. TASC1 8031"
tas:
  - name: "Yasaman Etasam"
    email: yetesam
    officehour: "Time: Fri 1/17 3:30pm-4:30pm, regularly Mon 2-3pm. Location: ASB9808"
  - name: "Ali Gholami"
    email: gholami
    officehour: "Time: Tues 1-2pm. Location: ASB9808"
  - name: "Roya Javadi"
    email: rjavadi
    officehour: "Time: Thu 9:30-10:30am. Location: ASB9808"
hwdates:
  - hw: "0"
    startdate: "Jan 9, 2020"
    deadline: "Jan 16, 2020"
  - hw: "1"
    startdate: "Jan 16, 2020"
    deadline: "Jan 30, 2020"
  - hw: "2"
    startdate: "Jan 30, 2020"
    deadline: "Feb 13, 2020"
  - hw: "3"
    startdate: "Feb 20, 2020"
    deadline: "Mar 5, 2020"
  - hw: "4"
    startdate: "Mar 5, 2020"
    deadline: "Mar 19, 2020"
  - hw: "project"
    startdate: "Feb 20, 2020"
    deadline: "Apr 14, 2020"
    time: "Poster session: Apr ??, 2020. 4pm-5:30pm (Session 1) and 5:30pm-7pm (Session 2)"
    location: "TBD"
    proposal: "Mar 12, 2020"
    milestone: "Mar 26, 2020"
