exclude: ['README.md', 'assets/latex/', 'archive']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2020sp-cmpt-825-g1/"
semcode: 1201
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Apr 9, 2020"
midterm: "Feb 20, 2020"
instructor: angel
tas:
  - name: "Yasaman Etasam"
    email: yetesam
    officehour: "Time: TBD. Location: TBD"
  - name: "Ali Gholami"
    email: gholami
    officehour: "Time: TBD. Location: TBD"
  - name: "Roya Javadi"
    email: rjavadi
    officehour: "Time: TBD. Location: TBD"
hwdates:
  - hw: "0"
    startdate: "Sep 10, 2019"
    deadline: "Sep 17, 2019"
  - hw: "1"
    startdate: "Sep 17, 2019"
    deadline: "Oct 1, 2019"
  - hw: "2"
    startdate: "Oct 1, 2019"
    deadline: "Oct 15, 2019"
  - hw: "3"
    startdate: "Oct 24, 2019"
    deadline: "Nov 7, 2019"
  - hw: "4"
    startdate: "Nov 7, 2019"
    deadline: "Nov 21, 2019"
  - hw: "project"
    startdate: "Oct 22, 2019"
    deadline: "Dec 9, 2019, 3pm"
    time: "Poster session: Dec 8, 2019. 4pm-5:30pm (Session 1) and 5:30pm-7pm (Session 2)"
    location: "[Fairmont Waterfront](https://www.fairmont.com/waterfront-vancouver/)."
    proposal: "Nov 12, 2019"
