exclude: ['README.md', 'assets/latex/', 'archive']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2020fa-cmpt-413-x1/"
piazza: "https://piazza.com/sfu.ca/fall2020/cmpt413825"
canvas: "https://canvas.sfu.ca/courses/56551"
semcode: 1207
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Dec 4, 2020"
midterm: "None"
instructor: angelx
officehour: "Time: Wed 2-3pm"
tas:
  - name: "Ali Gholami"
    email: gholami
    officehour: "Time: Mon 3-4pm"
  - name: "Sonia Raychaudhuri"
    email: sraychau
    officehour: "Time: Thurs 3-4pm"
  - name: "Yue Ruan"
    email: yuer
    officehour: "Time: Tues 3-4pm"
tutorials:
  - tutorial: "0"
    title: "Probability, linear algebra and calculus"
  - tutorial: "1"
    title: "Python/numpy"
  - tutorial: "2"
    title: "Classifiers"
  - tutorial: "3"
    title: "Optimization"
  - tutorial: "4"
    title: "Word Vectors"
  - tutorial: "5"
    title: "Pytorch and backpropagation"
  - tutorial: "6"
    title: "training/debugging networks and running experiments"
group:
  minsize: 2
  maxsize: 4
hwdates:
  - hw: "0"
    startdate: "Sept 9, 2020"
    deadline: "Sept 16, 2020"
    piazza: "http://www.piazza.com/class_profile/get_resource/kehwtnnb4g852t/kew9h6v5g6z44p"
  - hw: "1"
    startdate: "Sept 16, 2020"
    deadline: "Sept 30, 2020"
    piazza: "https://piazza.com/class_profile/get_resource/kehwtnnb4g852t/kf60wjoomek3a3"
  - hw: "2"
    startdate: "Sept 30, 2020"
    deadline: "Oct 14, 2020"
  - hw: "3"
    startdate: "Oct 14, 2020"
    deadline: "Oct 28, 2020"
  - hw: "4"
    startdate: "Oct 28, 2020"
    deadline: "Nov 11, 2020"
  - hw: "project"
    startdate: "Oct 3, 2020"
    deadline: "Dec 8, 2020"
    time: "Poster session: ???"
    location: "TBD"
    abstract: "Oct 16, 2020"
    proposal: "Oct 23, 2020"
    milestone: "Nov 20, 2020"
    poster: "TBD"
